### ISSUE TITLE
What is the point of the 'pipeline' block in the config?

### ISSUE THREAD

**Issue by nritsche** [radiocosmology/caput#112]
If there is no reason for it to exist, should we move the task section to the top level?

**Comment by nritsche** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [caput refactoring](https://trello.com/c/I2LkWOIe/6-caput-refactoring)

**Comment by ljgray** [comment]
I'm going to close this issue. I don't think it's a significant issue and changing it now would cause compatibility issues with old config files.
