### ISSUE TITLE
task._save_output should always overwrite versions

### ISSUE THREAD

**Issue by nritsche** [radiocosmology/caput#113]
versions in the metadata block should always be overwritten.
Should we always overwrite ALL metadata?
-> find out how hdf5 history works
Or rename config section to config.0 or similar

**Comment by nritsche** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [caput refactoring](https://trello.com/c/I2LkWOIe/6-caput-refactoring)

**Comment by ljgray** [comment]
Closing as this hasn't been updated for years and likely isn't relevant anymore
