### ISSUE TITLE
SkyfieldWrapper default expire is True

### ISSUE THREAD

**Issue by ashill** [radiocosmology/caput#125]
The documentation for `caput.time.SkyfieldWrapper` says that the default for the `expire` keyword is `False`. However:
```def __init__(self, path=None, expire=True, ephemeris="de421.bsp"):```
Either the documentation or the `__init__` command should be updated; I strongly prefer making `expire=False`.

**Comment by ashill** [comment]
@jrs65 Can this change be implemented? I tried, but don't have permission to push a pull request.

diff --git a/caput/time.py b/caput/time.py
index edd4ba5..4debaaf 100644
--- a/caput/time.py
+++ b/caput/time.py
@@ -764,7 +764,7 @@ class SkyfieldWrapper(object):
     reload
     """
 
-    def __init__(self, path=None, expire=True, ephemeris="de421.bsp"):
+    def __init__(self, path=None, expire=False, ephemeris="de421.bsp"):
 
         import os

**Comment by jrs65** [comment]
I'll give you permissions on radiocosmology to do that.. Although I think you can always fork, and then add a PR to the base repo.

**Comment by ashill** [comment]
PR #126
