### ISSUE TITLE
time.transit_times produces incorrect results with non-sensical interval and step size combinations

### ISSUE THREAD

**Issue by ketiltrout** [radiocosmology/caput#149]
Passing `time.transit_times` a small enough time range without also adjusting the step size (unsurprisingly) results in no transit being found:
```
>>> import datetime
>>> from caput.time import Observer
>>> Observer(lon=-119.62, lat=49.32, alt=545.0,lsd_start=datetime.datetime(2013, 11, 15)).transit_times(
        299.86815, 1.60660594e+09, 1.60660596e+09)
array([], dtype=float64)
```

Adjusting the step size to a reasonable value fixes this:
```
>>> Observer(lon=-119.62, lat=49.32, alt=545.0,lsd_start=datetime.datetime(2013, 11, 15)).transit_times(
        299.86815, 1.60660594e+09, 1.60660596e+09, step=4.6296296296296294e-05) 
array([1.60660595e+09])
```

This is the cause of a regression in `ch_util` (https://github.com/chime-experiment/ch_util/issues/40)

This function should raise an error if `step` is larger than the interval.  And I'd argue the best thing to do would be to make the default step size smaller (say, a fifth of the interval) in cases when the supplied interval is less than a day.

**Comment by jrs65** [comment]
Your suggested fix sounds reasonable. Feel free to submit a PR!
