### ISSUE TITLE
Why did we rename PipelineConfigError ?

### ISSUE THREAD

**Issue by tristpinsm** [radiocosmology/caput#155]
commit 8f2239934efde7712125ce2a14882c260f629e9f replaced `PipelineConfigError` with `CaputConfigError`. There are at least a few instances of this exception being used outside of `caput` (it is public after all), which are now broken. 

e.g.
```
$grep -r PipelineConfigError draco
draco/core/io.py:                raise pipeline.PipelineConfigError(
grep: draco/core/io.pyc: binary file matches
grep: draco/core/task.pyc: binary file matches
draco/core/task.py:            raise pipeline.PipelineConfigError(msg)
```

also in the beam code in `ch_pipeline` (which is where I noticed this)

**Comment by jrs65** [comment]
I think the ones in draco are changed in a corresponding PR that should have been merged by now. I'm not sure ch_pipeline was checked though. @nritsche maybe add an alias in caput for `PipelineConfigError =  CaputConfigError`, or add it back in but make it deprecated?

**Comment by tristpinsm** [comment]
I pulled the latest version of `master` on `draco` (radiocosmology/draco@43914e39d1046538c3ba0eafd993771095dcfebd) before checking.

**Comment by jrs65** [comment]
Oh oops. I guess Rick didn't catch everything. What was the rationale for the rename in the first place?

**Comment by nritsche** [comment]
> Oh oops. I guess Rick didn't catch everything. What was the rationale for the rename in the first place?

...adding config file line numbers to the error output, I think
