### ISSUE TITLE
Absolute referencing when creating memh5 dataset or group

### ISSUE THREAD

**Issue by jrs65** [radiocosmology/caput#16]
If you use create a memh5 dataset (or group) with an absolute path.

```python
gr = memh5.MemGroup()
gr.create_dataset('/data', data=np.arange(5))
```

Trying to fetch the dataset with `gr['data']` or `gr['/data']` will
fail as the creating does not actually attempt to do the absolute
referencing.

**Comment by kiyo-masui** [comment]
@jrs65 This seemed to already be implemented for groups (maybe you added it?) but I did the work for datasets.  I did something slightly sketch with `self = self.require_group(group_name)`. I think it is quite clever but could this break anything (especially with the distributed code)?

**Comment by jrs65** [comment]
I guess so. I don't remember it either!

I think that should be fine, and I don't think it should break the distributed stuff. It's maybe a little confusing though, I would have been tempted to define a `dataset_parent` variable which gets set to what you have done with `self` and then change all the uses of `self` below to `dataset_parent`. A little less confusing, as when you look at the code you don't get confused that `self` does not refer to the object you think it does.

**Comment by kiyo-masui** [comment]
Yeah, that is cleaner.  I'll do that.
