### ISSUE TITLE
Step through interactive runner for pipeline

### ISSUE THREAD

**Issue by kiyo-masui** [radiocosmology/caput#19]
It would be great if `caput.pipline.Manager` could be stepped through interactively.  One would have to break apart the `run()` method into a series of calls to a new method `next()`. The new method could return any outputs for the user to inspect (while still queueing them up for further processing).

In addition, it would be nice if there was a way to visualize the current state of the pipeline. Just a fancy print that gives the lengths of the queues, etc.

**Comment by jrs65** [comment]
One additional idea could be putting a `breakpoint: True` into the YAML file, such that it drops into an interactive mode. You could probably even force it to drop into pdb.
