### ISSUE TITLE
`memh5.from_group` does not have the expected behavior

### ISSUE THREAD

**Issue by leungcalvin** [radiocosmology/caput#190]
This bug was discovered downstream (in `baseband_analysis`) whose main data container `BBData` inherits from `BasicCont`. I tried to make a new, independent instance of a `BBData` object that lives in memory. I tried doing this using `from_group` but it looks like the new object created is, in fact, not a deep copy of the original (even though `from_group` calls something which is supposed to be `deep_group_copy`).

Modifying the datasets of the new object modifies the original. Is this the expected behavior? This is potentially dangerous for downstream analysis; tagging @jrs65 and @kiyo-masui because I'm so out of my depth here.

![image](https://user-images.githubusercontent.com/42367504/137636700-bdbb21b5-311d-4c60-80bf-0d42df84e0b3.png)

**Comment by jrs65** [comment]
For CHIME cosmology we built this functionality in at a higher level of abstraction into [draco.core.containers.ContainerBase.copy](https://github.com/radiocosmology/draco/blob/5d3bd9144d37f6cac9c80d4f07c242c699e177b0/draco/core/containers.py#L408), so we've never really noticed it was missing.

I think we could feasibly move the functionality down to a lower level (probably BasicCont) though if that would be helpful. It would require a little bit of refactoring, but provided the API remained the same I don't think we would care.

**Comment by ljgray** [comment]
@ketiltrout
