### ISSUE TITLE
More flexible pipelines by allowing variable number of outputs.

### ISSUE THREAD

**Issue by kiyo-masui** [radiocosmology/caput#20]
One weakness of the pipeline identified by @jrs65 is that it is impossible to split data: turn a single input into two outputs with the same type and key. One way to fix this might be to allow variable numbers of outputs.  The proposed syntax in the pipeline files is something like:

```
pipeline :
    tasks:
        -   type:   GetEggs
            params: eggs_params
            out:    *eggs
        -   type:   SpamAndEggs
            params: eggs_params
            out:    spam, ham, *eggs
```

Here, the first task may yield any number of outputs, all of which are added to the "eggs" queue for any task with that input key. The second task must yield at least two outputs (I suppose no output could also be allowed), added the the spam and ham queues respectively with any additional outputs are added to the eggs queue.

My questions for Richard are: would this solve your use cases? Does this solve any or your issues? All of them?

**Comment by kiyo-masui** [comment]
Turns out that we can't use "*", since that is a reference in YAML. Too bad since it nicely matches python syntax.

**Comment by jrs65** [comment]
That might be useful though I'm not sure it solves that many of my use cases. Not in a fundamental way, it's just that most of the tasks I can imagine that want to give output more frequently than they get input, have large outputs (in terms of memory), and this would force them all to be generated at one time.

**Comment by kiyo-masui** [comment]
Ahh, I see. We can sit on this one then and see if we can come up with something better.

Although doesn't this often mean that you don't have to store the input over multiple iterations? If the input size is the same as the output, then its a wash.

**Comment by ljgray** [comment]
The last discussion on this issue was in 2015, so I'm going to close it
