### ISSUE TITLE
CI tests fail with pytest 8.0.0

### ISSUE THREAD

**Issue by ljgray** [radiocosmology/caput#262]
Pytest 8.0.0 was released within the last week, along with pluggy 1.4.0. It now warns about old-style hook wrappers, causing our tests to fail with some fairly cryptic messages. See https://github.com/pytest-dev/pluggy/issues/463

Pytest Release Notes: https://docs.pytest.org/en/stable/changelog.html
Pluggy docs: https://pluggy.readthedocs.io/en/stable/index.html#wrappers
Pluggy Release Notes: https://pluggy.readthedocs.io/en/stable/changelog.html#features

The issues are coming from https://github.com/pytest-dev/pluggy/issues/463 but I'm not yet sure about whether there's a fix needed on our end or if we should be waiting on a new pytest release.

For the time being, I've pinned `pytest < 8.0.0` and `pluggy < 1.4.0` in #261

**Comment by jrs65** [comment]
Fixed in #253 by replacing pytest-lazy-fixture with pytest-lazy-fixture**s** following suggestion in https://github.com/TvoroG/pytest-lazy-fixture/issues/65#issuecomment-1925340355
