### ISSUE TITLE
Warning: mpi4py not installed.

### ISSUE THREAD

**Issue by ketiltrout** [radiocosmology/caput#46]
There needs to be a way to disable this warning message.  It's now spamming up bao's server logs:

```
/usr/local/lib/python2.7/dist-packages/caput/mpiutil.py:77: UserWarning: Warning: mpi4py not installed.
  warnings.warn("Warning: mpi4py not installed.")
/usr/local/lib/python2.7/dist-packages/caput/mpiutil.py:77: UserWarning: Warning: mpi4py not installed.
  warnings.warn("Warning: mpi4py not installed.")
```

I don't know what the normal idiom for selecting python module import behaviour is, but I'd be happy with an environmental variable, or something:
```
HEY_CAPUT_I_REALLY_DONT_CARE_ABOUT_MPI4PY=1 python
```

**Comment by jrs65** [comment]
I'm not sure what to do about this one. The warning is generated when you import `mpiutil` but you don't have `mpi4py` installed, and I think that's probably the right thing to do. Usually the code that does the import should disable the warning if having a working mpi setup is not important.

**Comment by jrs65** [comment]
Looking at it, it seems that the place we likely want to fix is `ch_util/connectdb.py` line 183. Just wrap it in a `warnings.catch_warnings` block.

**Comment by ketiltrout** [comment]
Yeah, that's a better fix.

**Comment by ketiltrout** [comment]
I'll update ch_util, but my reading of [the docs](https://docs.python.org/2/library/warnings.html#warning-categories) is that this should be an instance of ImportWarning, not the base class, i.e. the offending line should be
```
warnings.warn("Warning: mpi4py not installed.", ImportWarning)
```
which by default is going to be ignored unless you first unignore ImportWarning.

**Comment by jrs65** [comment]
That's a fair point. I guess we should change that line and the one that happens when skyfield cannot be imported.
