### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by fleaf5** [radiocosmology/caput#78]
When running pip install in frb-analysis, running into the following error: 
  
ERROR: Cannot unpack file /tmp/pip-unpack-sri9xqd6/caput.git (downloaded from /tmp/pip-req-build-raznthb7, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-raznthb7

**Comment by jrs65** [comment]
It doesn't look like you are running the correct command to install it. Can you send exactly what you ran?

Typically you would do something like:

pip install git+https://github.com/radiocosmology/caput.git
